config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/claytharrison/dask-flood-mapper:
      branch: virtual-zarr
      repo: https://github.com/claytharrison/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/claytharrison/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-cobalt-seahorse.sh
        container: qc.acc_leaky-scarlet-gecko
  QC.Doc:
    repos:
      github.com/claytharrison/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-viridian-seal.sh
        container: qc.doc_sickly-lemon-scorpion
      github.com/claytharrison/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cream-zebu.sh
        container: qc.doc_cranky-amber-scorpion
      github.com/claytharrison/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-russet-hamster.sh
        container: qc.doc_flimsy-lilac-audemer
      github.com/claytharrison/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-persimmon-dodo.sh
        container: qc.doc_beady-bistre-sheepdog
  QC.Lic:
    repos:
      github.com/claytharrison/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.messy-corn-chipmunk.sh
        container: qc.lic_grumpy-bronze-liger
  QC.Met:
    repos:
      github.com/claytharrison/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.randy-cyan-wolfhound.sh
        container: qc.met_wiggy-denim-heron
  QC.Sec:
    repos:
      github.com/claytharrison/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-indigo-cat.sh
        container: qc.sec_greasy-gamboge-bombay
  QC.Sty:
    repos:
      github.com/claytharrison/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-beige-newfoundland.sh
        container: qc.sty_fuzzy-cerise-frigatebird
      github.com/claytharrison/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-burgundy-octopus.sh
        container: qc.sty_gummy-violet-bandicoot
      github.com/claytharrison/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-carmine-heron.sh
        container: qc.sty_flimsy-chocolate-moose
  QC.Uni:
    repos:
      github.com/claytharrison/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-champagne-spaniel.sh
        container: qc.uni_stealthy-pumpkin-retriever
  QC.Ver:
    repos:
      github.com/claytharrison/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-khaki-quetzal.sh
        container: qc.ver_sloppy-heliotrope-octopus
timeout: 5400
