config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: fix-release-url
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-cream-lynx.sh
        container: qc.acc_hazy-corn-grouse
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-cerulean-gorilla.sh
        container: qc.doc_wiggy-buff-orangutan
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-red-abyssinian.sh
        container: qc.doc_skinny-peach-otter
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-sepia-reindeer.sh
        container: qc.doc_shaggy-tomato-turtle
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-black-ray.sh
        container: qc.doc_frumpy-lime-walrus
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-corn-insect.sh
        container: qc.lic_gimpy-smalt-burmese
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-wheat-owl.sh
        container: qc.met_tacky-burgundy-gar
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-maroon-termite.sh
        container: qc.sec_hazy-chocolate-heron
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-aqua-coati.sh
        container: qc.sty_gamy-harlequin-seal
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-magenta-eagle.sh
        container: qc.sty_nippy-cerulean-leopard
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-persimmon-crocodile.sh
        container: qc.sty_squeaky-jade-dollar
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-copper-crane.sh
        container: qc.uni_skimpy-periwinkle-cuscus
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-bistre-bordeaux.sh
        container: qc.ver_boozy-ecru-cuscus
timeout: 5400
