config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: virtual-zarr
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-mauve-shrimp.sh
        container: qc.acc_stealthy-violet-quail
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-silver-bandicoot.sh
        container: qc.doc_wiggy-green-bulldog
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-alizarin-jackal.sh
        container: qc.doc_snoopy-seashell-urchin
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-cerise-birman.sh
        container: qc.doc_trippy-tan-dalmatian
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-copper-grasshopper.sh
        container: qc.doc_dorky-yellow-olm
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-alizarin-wallaby.sh
        container: qc.lic_droopy-lilac-turtle
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-lavender-gerbil.sh
        container: qc.met_beady-olive-grouse
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-maroon-impala.sh
        container: qc.sec_squeaky-platinum-manatee
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-khaki-dachshund.sh
        container: qc.sty_woozy-russet-quokka
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-platinum-markhor.sh
        container: qc.sty_smelly-aqua-caterpillar
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-plum-raccoon.sh
        container: qc.sty_wimpy-cornflower-gibbon
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-olive-goat.sh
        container: qc.uni_tacky-seashell-vulture
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-aqua-donkey.sh
        container: qc.ver_muggy-eggplant-rabbit
timeout: 5400
