config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: workshop-modified
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-lilac-tamarin.sh
        container: qc.acc_baggy-green-zorse
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-corn-ibis.sh
        container: qc.doc_blurry-beige-bombay
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-linen-dragon.sh
        container: qc.doc_chewy-taupe-bordeaux
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-copper-binturong.sh
        container: qc.doc_leaky-xanthic-macaque
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-champagne-cougar.sh
        container: qc.lic_stealthy-lavender-gharial
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-mustard-woodlouse.sh
        container: qc.met_wheezy-seashell-reindeer
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-puce-bandicoot.sh
        container: qc.sec_stuffy-seashell-abyssinian
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-burgundy-hare.sh
        container: qc.sty_randy-crimson-shark
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-ruby-ant.sh
        container: qc.sty_bluesy-bronze-birman
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-thistle-avocet.sh
        container: qc.sty_tacky-black-chinook
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.homely-periwinkle-bonobo.sh
        container: qc.uni_sloppy-denim-ibis
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-alizarin-kudu.sh
        container: qc.ver_dorky-platinum-spitz
timeout: 5400
