config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: main
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-crimson-horse.sh
        container: qc.acc_bumpy-seashell-axolotl
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-platinum-bobcat.sh
        container: qc.doc_flimsy-brown-boar
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-corn-tetra.sh
        container: qc.doc_cloudy-asparagus-retriever
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-magnolia-anteater.sh
        container: qc.doc_lousy-charcoal-fowl
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-crimson-guppy.sh
        container: qc.doc_whiny-rust-badger
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-wisteria-gibbon.sh
        container: qc.lic_nerdy-champagne-warthog
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-mustard-penguin.sh
        container: qc.met_beady-orange-gopher
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-puce-dugong.sh
        container: qc.sec_skinny-tan-dragonfly
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.beady-cornflower-millipede.sh
        container: qc.sty_silly-seashell-donkey
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-charcoal-spider.sh
        container: qc.sty_seedy-brass-otter
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-ivory-tapir.sh
        container: qc.sty_nippy-ecru-retriever
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-green-turkey.sh
        container: qc.uni_bumpy-peach-tzu
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-cream-cichlid.sh
        container: qc.ver_ugly-taupe-argentino
timeout: 5400
