config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia-test
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: workshop-modified
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-charcoal-fousek.sh
        container: qc.acc_cloudy-cerulean-audemer
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-puce-alligator.sh
        container: qc.doc_flimsy-linen-ragdoll
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-amaranth-hedgehog.sh
        container: qc.doc_muzzy-olivine-chihuahua
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-cardinal-crocodile.sh
        container: qc.doc_tacky-lemon-liger
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-wisteria-cockroach.sh
        container: qc.lic_crappy-vermilion-blue
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-salmon-buzzard.sh
        container: qc.met_frumpy-razzmatazz-dragon
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-thistle-oyster.sh
        container: qc.sec_bluesy-seashell-swan
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-beige-coati.sh
        container: qc.sty_shabby-wisteria-hare
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-smalt-lizard.sh
        container: qc.sty_shaky-cardinal-shrimp
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-ultramarine-elephant.sh
        container: qc.sty_pretty-smalt-mammoth
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-flax-camel.sh
        container: qc.uni_jumpy-sangria-harrier
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-ivory-neanderthal.sh
        container: qc.ver_craggy-red-squid
timeout: 5400
