config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: thaisbeham-patch-2
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-alizarin-barb.sh
        container: qc.acc_tacky-gamboge-koala
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-apricot-dolphin.sh
        container: qc.doc_craggy-maroon-grasshopper
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-ultramarine-drever.sh
        container: qc.doc_greasy-jade-bison
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-olive-owl.sh
        container: qc.doc_trippy-silver-vole
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-khaki-octopus.sh
        container: qc.doc_beady-burgundy-jackal
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-amethyst-mandrill.sh
        container: qc.lic_grumpy-buff-toad
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-heliotrope-worm.sh
        container: qc.met_bluesy-cornflower-maltese
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-pear-heron.sh
        container: qc.sec_scummy-cream-rottweiler
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.randy-harlequin-cichlid.sh
        container: qc.sty_skanky-grey-manatee
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-lilac-snail.sh
        container: qc.sty_cloudy-cinnamon-toucan
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-bronze-pig.sh
        container: qc.sty_pretty-lavender-mongrel
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-emerald-quokka.sh
        container: qc.uni_homey-razzmatazz-bat
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-firebrick-dolphin.sh
        container: qc.ver_jumpy-pink-bulldog
timeout: 5400
