config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: thaisbeham-patch-2
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-corn-blue.sh
        container: qc.acc_skinny-azure-monster
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-vermilion-hare.sh
        container: qc.doc_shabby-persimmon-oyster
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-wheat-corgi.sh
        container: qc.doc_geeky-ochre-fly
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-turquoise-pig.sh
        container: qc.doc_goopy-ultramarine-tzu
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-red-koala.sh
        container: qc.doc_stuffy-burgundy-iguana
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-orchid-rabbit.sh
        container: qc.lic_scummy-brown-fossa
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-russet-saola.sh
        container: qc.met_muggy-plum-moose
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-persimmon-gar.sh
        container: qc.sec_skinny-gold-moose
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-denim-crane.sh
        container: qc.sty_gimpy-cardinal-camel
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-viridian-lemming.sh
        container: qc.sty_homey-aquamarine-whale
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-eggplant-wasp.sh
        container: qc.sty_thirsty-lime-urchin
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-saffron-affenpinscher.sh
        container: qc.uni_seedy-cinnabar-penguin
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-ultramarine-hornet.sh
        container: qc.ver_crabby-charcoal-whale
timeout: 5400
