config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: sqaaas
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-burgundy-echidna.sh
        container: qc.acc_slaphappy-cobalt-uakari
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-copper-tiger.sh
        container: qc.doc_seedy-mauve-fossa
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-burgundy-dog.sh
        container: qc.doc_frumpy-amethyst-oriole
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-seashell-avocet.sh
        container: qc.doc_shaky-coral-newfoundland
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-cinnamon-rabbit.sh
        container: qc.doc_gamy-brass-setter
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-firebrick-neanderthal.sh
        container: qc.lic_snappy-chocolate-oyster
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-olive-cassowary.sh
        container: qc.met_hasty-celadon-dragonfly
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-vermilion-wallaby.sh
        container: qc.sec_shaky-charcoal-rottweiler
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-lime-dog.sh
        container: qc.sty_scaly-goldenrod-vulture
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-viridian-chinchilla.sh
        container: qc.sty_goopy-rust-lizard
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-goldenrod-earwig.sh
        container: qc.sty_jumpy-maroon-binturong
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-emerald-tamarin.sh
        container: qc.uni_homely-ecru-seahorse
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-wheat-frigatebird.sh
        container: qc.ver_lousy-sepia-blue
timeout: 5400
