config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: workshop-f
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-white-butterfly.sh
        container: qc.acc_cheeky-emerald-rat
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-chestnut-chimpanzee.sh
        container: qc.doc_sickly-plum-dragon
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-flax-wildebeest.sh
        container: qc.doc_paltry-celadon-snail
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-black-moose.sh
        container: qc.doc_jumpy-ochre-termite
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-vermilion-moose.sh
        container: qc.lic_ready-malachite-wildebeest
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-salmon-catfish.sh
        container: qc.met_woozy-cyan-toucan
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-vermilion-avocet.sh
        container: qc.sec_woozy-charcoal-bullfrog
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-brass-kakapo.sh
        container: qc.sty_paltry-heliotrope-alligator
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-gamboge-sponge.sh
        container: qc.sty_nippy-khaki-kudu
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-cobalt-dugong.sh
        container: qc.sty_thirsty-purple-chihuahua
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-flax-stoat.sh
        container: qc.uni_sickly-lilac-wombat
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-chocolate-gerbil.sh
        container: qc.ver_cheeky-magenta-toucan
timeout: 5400
