config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: sqaaas
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-beige-abyssinian.sh
        container: qc.acc_grumpy-azure-angora
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-tangerine-orangutan.sh
        container: qc.doc_scummy-wisteria-falcon
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-ruby-gar.sh
        container: qc.doc_gamy-black-millipede
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-platinum-ocelot.sh
        container: qc.doc_flaky-chestnut-quetzal
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-aqua-spoonbill.sh
        container: qc.doc_skanky-persimmon-toad
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-beige-kiwi.sh
        container: qc.lic_freaky-persimmon-chihuahua
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-goldenrod-affenpinscher.sh
        container: qc.met_greasy-sapphire-mau
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-lavender-llama.sh
        container: qc.sec_frumpy-bronze-gorilla
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-seashell-seal.sh
        container: qc.sty_crappy-persimmon-tarantula
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-chestnut-cow.sh
        container: qc.sty_chummy-purple-squirt
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-cerise-kakapo.sh
        container: qc.sty_hasty-linen-serval
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-wisteria-fossa.sh
        container: qc.uni_gloppy-harlequin-tang
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-tan-clam.sh
        container: qc.ver_snippy-flax-gerbil
timeout: 5400
