config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: workshop
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-myrtle-molly.sh
        container: qc.acc_skanky-sapphire-toad
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-rose-hyrax.sh
        container: qc.doc_slaphappy-ruby-zorse
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-aquamarine-crab.sh
        container: qc.doc_scaly-cornflower-crane
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-aquamarine-bulldog.sh
        container: qc.doc_hazy-plum-chicken
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-gold-owl.sh
        container: qc.lic_homely-heliotrope-molly
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cyan-okapi.sh
        container: qc.met_pretty-mauve-dormouse
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-brass-audemer.sh
        container: qc.sec_foggy-brass-hyena
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-fuchsia-ant.sh
        container: qc.sty_sickly-sapphire-pig
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-thistle-mammoth.sh
        container: qc.sty_sleepy-tangerine-dragonfly
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-lemon-slug.sh
        container: qc.sty_baggy-amethyst-zebu
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-brass-capybara.sh
        container: qc.uni_freaky-zucchini-spaniel
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-linen-hippopotamus.sh
        container: qc.ver_queasy-blue-mayfly
timeout: 5400
