config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: thaisbeham-patch-2-1
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-lilac-paradise.sh
        container: qc.acc_gamy-cobalt-harrier
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-malachite-centipede.sh
        container: qc.doc_skanky-black-magpie
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-puce-octopus.sh
        container: qc.doc_homey-razzmatazz-gopher
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-brass-magpie.sh
        container: qc.doc_frumpy-aquamarine-dugong
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-amaranth-catfish.sh
        container: qc.doc_homely-ivory-rat
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-wheat-spoonbill.sh
        container: qc.lic_hilly-sangria-dane
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-rust-civet.sh
        container: qc.met_surly-cardinal-turkey
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-myrtle-butterfly.sh
        container: qc.sec_crappy-charcoal-woodlouse
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-magnolia-chihuahua.sh
        container: qc.sty_cozy-alizarin-sheepdog
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-saffron-drever.sh
        container: qc.sty_scaly-coral-fousek
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-emerald-hare.sh
        container: qc.sty_bluesy-smalt-urchin
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.ready-brown-boar.sh
        container: qc.uni_wimpy-indigo-spider
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-wisteria-bullfrog.sh
        container: qc.ver_cranky-denim-termite
timeout: 5400
