config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: thaisbeham-patch-2
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-white-dachshund.sh
        container: qc.acc_homey-lilac-shrimp
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-ivory-dogfish.sh
        container: qc.doc_cozy-brass-dingo
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-plum-fousek.sh
        container: qc.doc_muggy-bistre-clam
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-burgundy-zebu.sh
        container: qc.doc_surly-asparagus-slug
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-salmon-hyena.sh
        container: qc.doc_sunny-chocolate-chinchilla
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.messy-cinnabar-monster.sh
        container: qc.lic_lumpy-rose-camel
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-pink-quail.sh
        container: qc.met_stinky-mauve-blue
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cyan-grouse.sh
        container: qc.sec_nerdy-xanthic-tuatara
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-mauve-urchin.sh
        container: qc.sty_frumpy-wheat-mandrill
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-brown-bird.sh
        container: qc.sty_leaky-turquoise-ostrich
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-magenta-kudu.sh
        container: qc.sty_crabby-grey-spaniel
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-tomato-crocodile.sh
        container: qc.uni_muzzy-zucchini-slug
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-mauve-blue.sh
        container: qc.ver_snoopy-tomato-skunk
timeout: 5400
