config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: workshop
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-azure-cougar.sh
        container: qc.acc_paltry-brown-dragonfly
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-buff-newfoundland.sh
        container: qc.doc_cranky-xanthic-fly
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-olivine-birman.sh
        container: qc.doc_flimsy-zucchini-deer
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-azure-loon.sh
        container: qc.doc_bluesy-cerulean-balinese
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homey-chartreuse-mouse.sh
        container: qc.lic_snippy-olivine-malamute
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-taupe-rat.sh
        container: qc.met_fuzzy-seashell-booby
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-azure-cuttlefish.sh
        container: qc.sec_greasy-amethyst-eleuth
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-salmon-gar.sh
        container: qc.sty_sloppy-apricot-anteater
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-silver-dragonfly.sh
        container: qc.sty_woolly-indigo-orangutan
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-mustard-zebra.sh
        container: qc.sty_hilly-denim-ladybird
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-ruby-gorilla.sh
        container: qc.uni_sickly-sepia-affenpinscher
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-red-pig.sh
        container: qc.ver_ugly-lilac-russel
timeout: 5400
