config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: workshop
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-bistre-warthog.sh
        container: qc.acc_sleepy-silver-capuchin
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-alizarin-hornet.sh
        container: qc.doc_flaky-salmon-mole
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-cornflower-capybara.sh
        container: qc.doc_shaggy-orange-newfoundland
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-chestnut-salamander.sh
        container: qc.doc_wimpy-myrtle-snail
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-ochre-hyrax.sh
        container: qc.lic_foggy-chocolate-squid
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-magenta-woodpecker.sh
        container: qc.met_goopy-cerise-ocelot
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-taupe-macaque.sh
        container: qc.sec_frumpy-smalt-dragonfly
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-flax-dachsbracke.sh
        container: qc.sty_slimy-taupe-booby
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-purple-swan.sh
        container: qc.sty_scaly-plum-gecko
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-burgundy-liger.sh
        container: qc.sty_flabby-olive-jackal
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cornflower-barb.sh
        container: qc.uni_shaky-emerald-llama
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-pumpkin-wombat.sh
        container: qc.ver_flaky-champagne-maltese
timeout: 5400
