config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: dev-update-image
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-lime-scorpion.sh
        container: qc.acc_hazy-olivine-leopard
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-brown-olm.sh
        container: qc.doc_hasty-lilac-axolotl
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-aqua-frog.sh
        container: qc.doc_ugly-platinum-dormouse
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-khaki-wolf.sh
        container: qc.doc_crappy-flax-fox
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-razzmatazz-burmese.sh
        container: qc.doc_baggy-red-mayfly
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-celadon-newt.sh
        container: qc.lic_boozy-persimmon-foxhound
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-taupe-zebu.sh
        container: qc.met_gloppy-buff-neanderthal
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.beady-ivory-gecko.sh
        container: qc.sec_hasty-purple-seahorse
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-persimmon-zorse.sh
        container: qc.sty_greasy-tan-monster
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-chestnut-dachshund.sh
        container: qc.sty_craggy-corn-caterpillar
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-red-octopus.sh
        container: qc.sty_messy-black-moth
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-olivine-ostrich.sh
        container: qc.uni_pasty-amethyst-ocelot
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-ivory-fly.sh
        container: qc.ver_clammy-burgundy-tamarin
timeout: 5400
