config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: thaisbeham-patch-2
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-puce-heron.sh
        container: qc.acc_sunny-viridian-tetra
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-coral-seal.sh
        container: qc.doc_baggy-saffron-owl
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-goldenrod-whippet.sh
        container: qc.doc_lanky-flax-spoonbill
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-aquamarine-chamois.sh
        container: qc.doc_scanty-orange-gar
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-emerald-caracal.sh
        container: qc.doc_leaky-yellow-coati
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-alizarin-goat.sh
        container: qc.lic_snappy-orange-olm
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-pink-binturong.sh
        container: qc.met_droopy-chocolate-wolverine
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-burgundy-crocodile.sh
        container: qc.sec_gimpy-bistre-chin
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-alizarin-moth.sh
        container: qc.sty_stinky-champagne-termite
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-indigo-mongoose.sh
        container: qc.sty_snippy-mauve-panda
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-tangerine-heron.sh
        container: qc.sty_gimpy-dandelion-stingray
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-purple-moorhen.sh
        container: qc.uni_crabby-cardinal-yak
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-rust-fowl.sh
        container: qc.ver_droopy-magnolia-molly
timeout: 5400
