config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: main
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-denim-fossa.sh
        container: qc.acc_thirsty-cinnamon-cichlid
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-crimson-caterpillar.sh
        container: qc.doc_muggy-persimmon-ibis
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-blue-goose.sh
        container: qc.doc_slimy-dandelion-stoat
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-bronze-oriole.sh
        container: qc.doc_freaky-lime-labradoodle
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-cerise-collie.sh
        container: qc.doc_blurry-cinnabar-bird
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-sepia-newt.sh
        container: qc.lic_zippy-asparagus-chinchilla
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-chestnut-fossa.sh
        container: qc.met_bluesy-corn-hyena
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-goldenrod-bracke.sh
        container: qc.sec_sloppy-crimson-chin
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-vermilion-spitz.sh
        container: qc.sty_slaphappy-champagne-monster
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-cornflower-magpie.sh
        container: qc.sty_tasty-white-foxhound
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-scarlet-earwig.sh
        container: qc.sty_skinny-ivory-termite
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-goldenrod-numbat.sh
        container: qc.uni_blurry-beige-deer
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-celadon-schnauzer.sh
        container: qc.ver_sickly-coral-saola
timeout: 5400
