config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: main
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-periwinkle-crocodile.sh
        container: qc.acc_sickly-persimmon-oyster
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-eggplant-capuchin.sh
        container: qc.doc_clammy-copper-angora
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-taupe-zorse.sh
        container: qc.doc_craggy-wisteria-argentino
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-tangerine-dachsbracke.sh
        container: qc.doc_foggy-harlequin-dragonfly
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-russet-monkey.sh
        container: qc.doc_homey-cornflower-zebu
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-carmine-butterfly.sh
        container: qc.lic_shaggy-red-cassowary
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-gamboge-liger.sh
        container: qc.met_homey-cyan-snake
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-eggplant-crane.sh
        container: qc.sec_baggy-razzmatazz-lion
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-viridian-whippet.sh
        container: qc.sty_zippy-aqua-meerkat
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-peach-lemming.sh
        container: qc.sty_tasty-teal-angelfish
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-olive-bloodhound.sh
        container: qc.sty_cheeky-khaki-ostrich
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-tangerine-cuscus.sh
        container: qc.uni_ready-cerulean-bongo
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-khaki-orangutan.sh
        container: qc.ver_fuzzy-ruby-squid
timeout: 5400
