config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: main
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-burgundy-squirrel.sh
        container: qc.acc_jumpy-russet-cichlid
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-flax-antelope.sh
        container: qc.doc_lumpy-brass-snake
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-ochre-squid.sh
        container: qc.doc_hasty-copper-impala
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-black-mastiff.sh
        container: qc.doc_jumpy-rust-clam
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-aqua-cow.sh
        container: qc.doc_grumpy-ochre-nightingale
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-ruby-markhor.sh
        container: qc.lic_skinny-celadon-saola
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-russet-chipmunk.sh
        container: qc.met_squirrely-malachite-bonobo
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-heliotrope-walrus.sh
        container: qc.sec_blurry-vermilion-hyena
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-rose-chipmunk.sh
        container: qc.sty_blurry-ruby-cougar
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-aquamarine-wallaby.sh
        container: qc.sty_zippy-xanthic-buzzard
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-purple-sheepdog.sh
        container: qc.sty_gloppy-cardinal-grouse
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-cardinal-toad.sh
        container: qc.uni_crabby-seashell-malamute
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-flax-iguana.sh
        container: qc.ver_flimsy-red-jellyfish
timeout: 5400
