config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/npikall/dask-flood-mapper:
      branch: dev-np
      repo: https://github.com/npikall/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/npikall/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-lavender-insect.sh
        container: qc.acc_surly-gold-woodlouse
  QC.Doc:
    repos:
      github.com/npikall/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-carmine-harrier.sh
        container: qc.doc_cloudy-corn-iguana
      github.com/npikall/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-grey-rabbit.sh
        container: qc.doc_geeky-aquamarine-quoll
      github.com/npikall/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-green-angelfish.sh
        container: qc.doc_skanky-viridian-macaw
      github.com/npikall/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-cinnamon-gharial.sh
        container: qc.doc_muzzy-silver-dog
  QC.Lic:
    repos:
      github.com/npikall/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-cerulean-budgerigar.sh
        container: qc.lic_scaly-emerald-cat
  QC.Met:
    repos:
      github.com/npikall/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-auburn-albatross.sh
        container: qc.met_cloudy-amber-koala
  QC.Sec:
    repos:
      github.com/npikall/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-chestnut-armadillo.sh
        container: qc.sec_shabby-olive-moose
  QC.Sty:
    repos:
      github.com/npikall/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-black-balinese.sh
        container: qc.sty_frumpy-green-mole
      github.com/npikall/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-aquamarine-stingray.sh
        container: qc.sty_silly-vermilion-bandicoot
      github.com/npikall/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-ochre-peccary.sh
        container: qc.sty_flabby-plum-monkey
  QC.Uni:
    repos:
      github.com/npikall/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-myrtle-warthog.sh
        container: qc.uni_gimpy-eggplant-lionfish
  QC.Ver:
    repos:
      github.com/npikall/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-vermilion-beagle.sh
        container: qc.ver_hazy-pear-ostrich
timeout: 5400
