config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: main
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-seashell-rat.sh
        container: qc.acc_pasty-ruby-chipmunk
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-charcoal-fox.sh
        container: qc.doc_craggy-brass-seahorse
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-cerulean-sparrow.sh
        container: qc.doc_flimsy-orchid-chamois
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-cream-whippet.sh
        container: qc.doc_squirrely-brass-chinook
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-amethyst-mongrel.sh
        container: qc.doc_skimpy-scarlet-barnacle
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-goldenrod-snail.sh
        container: qc.lic_trippy-grey-dunker
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-pink-kiwi.sh
        container: qc.met_clammy-olivine-chin
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-rust-stoat.sh
        container: qc.sec_leaky-bistre-badger
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-magnolia-tzu.sh
        container: qc.sty_sickly-scarlet-eel
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-magnolia-maltese.sh
        container: qc.sty_paltry-ultramarine-emu
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-peach-woodlouse.sh
        container: qc.sty_pokey-azure-flamingo
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.homely-magenta-blue.sh
        container: qc.uni_wimpy-green-chipmunk
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-wheat-crab.sh
        container: qc.ver_cozy-beige-buffalo
timeout: 5400
