config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: workshop
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-scarlet-foxhound.sh
        container: qc.acc_sickly-maroon-sparrow
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-asparagus-crab.sh
        container: qc.doc_nippy-celadon-fly
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-corn-caiman.sh
        container: qc.doc_sunny-black-javanese
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-copper-gar.sh
        container: qc.doc_woolly-champagne-tuatara
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-cardinal-dragon.sh
        container: qc.lic_bumpy-fuchsia-tamarin
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-apricot-caracal.sh
        container: qc.met_bumpy-fuchsia-bulldog
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cyan-shark.sh
        container: qc.sec_cloudy-scarlet-grasshopper
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-viridian-warthog.sh
        container: qc.sty_homey-fuchsia-emu
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cerulean-dragon.sh
        container: qc.sty_stinky-azure-mandrill
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-malachite-squirt.sh
        container: qc.sty_queasy-fuchsia-cassowary
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-ruby-tuatara.sh
        container: qc.uni_sleepy-aqua-zorse
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-magnolia-paradise.sh
        container: qc.ver_trippy-ruby-mastiff
timeout: 5400
