config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: dependabot/github_actions/actions/checkout-6
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-ruby-buzzard.sh
        container: qc.acc_muggy-eggplant-mayfly
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-denim-bonobo.sh
        container: qc.doc_boozy-champagne-newfoundland
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-malachite-chinook.sh
        container: qc.doc_snappy-olivine-bloodhound
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-jade-catfish.sh
        container: qc.doc_crappy-ruby-budgerigar
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-cream-boar.sh
        container: qc.doc_silly-burgundy-fossa
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-cinnabar-tarantula.sh
        container: qc.lic_foggy-bronze-bordeaux
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-olivine-newt.sh
        container: qc.met_smelly-smalt-cichlid
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-silver-vulture.sh
        container: qc.sec_stuffy-gold-dugong
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-ivory-shrew.sh
        container: qc.sty_nippy-chocolate-labradoodle
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-ruby-birman.sh
        container: qc.sty_slimy-zucchini-butterfly
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-tan-newfoundland.sh
        container: qc.sty_slaphappy-myrtle-tamarin
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-celadon-spaniel.sh
        container: qc.uni_scanty-coral-ostrich
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-seashell-moth.sh
        container: qc.ver_fuzzy-heliotrope-schnauzer
timeout: 5400
