config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: dependabot/github_actions/actions/checkout-4
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-teal-rabbit.sh
        container: qc.acc_shaggy-seashell-chinook
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-amaranth-catfish.sh
        container: qc.doc_messy-ivory-bee
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-rose-antelope.sh
        container: qc.doc_slimy-plum-flounder
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-zucchini-fowl.sh
        container: qc.doc_seedy-cinnabar-kiwi
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-denim-hyrax.sh
        container: qc.doc_grumpy-zucchini-antelope
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-plum-rhinoceros.sh
        container: qc.lic_fuzzy-denim-bonobo
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-lime-retriever.sh
        container: qc.met_hazy-pumpkin-cockroach
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ready-dandelion-ibis.sh
        container: qc.sec_gloppy-sapphire-crane
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-yellow-fossa.sh
        container: qc.sty_lovely-yellow-shrimp
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-persimmon-goat.sh
        container: qc.sty_goopy-pink-liger
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-vermilion-hare.sh
        container: qc.sty_woolly-auburn-nightingale
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-grey-buffalo.sh
        container: qc.uni_sunny-firebrick-burmese
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-brown-grouse.sh
        container: qc.ver_stuffy-auburn-birman
timeout: 5400
