config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: workshop-modified
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-harlequin-pig.sh
        container: qc.acc_scummy-alizarin-ray
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-bistre-otter.sh
        container: qc.doc_cloudy-charcoal-buzzard
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-salmon-termite.sh
        container: qc.doc_slimy-grey-chin
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-crimson-molly.sh
        container: qc.doc_sunny-rust-warthog
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-beige-mole.sh
        container: qc.lic_lumpy-yellow-badger
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-sapphire-beaver.sh
        container: qc.met_scaly-aquamarine-hamster
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-sepia-birman.sh
        container: qc.sec_cloudy-flax-dunker
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-sepia-badger.sh
        container: qc.sty_snippy-platinum-gerbil
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-violet-weasel.sh
        container: qc.sty_sloppy-viridian-hyena
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-silver-sheep.sh
        container: qc.sty_gamy-ivory-worm
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-cream-robin.sh
        container: qc.uni_jumpy-linen-toucan
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-olivine-bordeaux.sh
        container: qc.ver_ugly-pear-boar
timeout: 5400
