config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: thaisbeham-patch-3
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-sepia-capybara.sh
        container: qc.acc_flabby-tomato-crab
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-puce-avocet.sh
        container: qc.doc_hazy-carmine-scorpion
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-beige-dugong.sh
        container: qc.doc_seedy-green-axolotl
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-cyan-moorhen.sh
        container: qc.doc_snappy-viridian-robin
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-bistre-avocet.sh
        container: qc.doc_snazzy-amber-uakari
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-alizarin-greyhound.sh
        container: qc.lic_blurry-apricot-caterpillar
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-fuchsia-bee.sh
        container: qc.met_homely-sangria-rat
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-amaranth-sponge.sh
        container: qc.sec_paltry-alizarin-lizard
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homey-green-spider.sh
        container: qc.sty_randy-denim-flounder
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-emerald-mau.sh
        container: qc.sty_flimsy-gold-hyrax
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-burgundy-ibis.sh
        container: qc.sty_pokey-goldenrod-zebra
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper commands:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-seashell-discus.sh
        container: qc.uni_nippy-magnolia-hyena
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-fuchsia-birman.sh
        container: qc.ver_chewy-cornflower-wolverine
timeout: 5400
