config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: main
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-cream-monkey.sh
        container: qc.acc_lousy-bistre-gorilla
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-purple-bullfrog.sh
        container: qc.doc_cranky-pink-russel
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-grey-booby.sh
        container: qc.doc_woozy-ivory-dunker
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-pear-elephant.sh
        container: qc.doc_frumpy-grey-coyote
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-dandelion-coati.sh
        container: qc.doc_gloppy-alizarin-gar
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-thistle-blue.sh
        container: qc.lic_dorky-violet-dingo
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-viridian-cuttlefish.sh
        container: qc.met_geeky-red-frise
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-vermilion-squirrel.sh
        container: qc.sec_skinny-alizarin-antelope
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-flax-birman.sh
        container: qc.sty_beady-tomato-kingfisher
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-brass-dachshund.sh
        container: qc.sty_lumpy-pumpkin-beetle
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-rose-dragonfly.sh
        container: qc.sty_tacky-pear-olm
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.randy-wisteria-zorse.sh
        container: qc.uni_shaggy-grey-slug
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-magnolia-otter.sh
        container: qc.ver_lanky-teal-wombat
timeout: 5400
