config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: thaisbeham-patch-2-1
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-corn-pig.sh
        container: qc.acc_stealthy-xanthic-cockroach
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-salmon-leopard.sh
        container: qc.doc_flimsy-xanthic-bandicoot
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-platinum-baboon.sh
        container: qc.doc_pokey-platinum-cheetah
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-charcoal-greyhound.sh
        container: qc.doc_stinky-vermilion-kiwi
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-zucchini-sparrow.sh
        container: qc.doc_hilly-ecru-tortoise
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-aqua-stingray.sh
        container: qc.lic_hasty-plum-chamois
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-jade-snail.sh
        container: qc.met_tasty-smalt-setter
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-beige-buzzard.sh
        container: qc.sec_nippy-cream-fly
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-chocolate-turtle.sh
        container: qc.sty_snoopy-rose-beaver
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-seashell-zorse.sh
        container: qc.sty_beady-sapphire-kiwi
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-plum-molly.sh
        container: qc.sty_homey-ochre-peccary
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper commands:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-orchid-shrimp.sh
        container: qc.uni_pokey-linen-bordeaux
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-plum-cassowary.sh
        container: qc.ver_muggy-xanthic-gopher
timeout: 5400
