config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/npikall/dask-flood-mapper:
      branch: dev-np
      repo: https://github.com/npikall/dask-flood-mapper/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/npikall/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-tangerine-tuatara.sh
        container: qc.acc_jumpy-purple-wombat
  QC.Doc:
    repos:
      github.com/npikall/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-periwinkle-monkey.sh
        container: qc.doc_tacky-cinnamon-raccoon
      github.com/npikall/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-auburn-terrier.sh
        container: qc.doc_woozy-periwinkle-scorpion
      github.com/npikall/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-sangria-warthog.sh
        container: qc.doc_sloppy-auburn-dingo
      github.com/npikall/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-purple-akita.sh
        container: qc.doc_seedy-ivory-reindeer
  QC.Lic:
    repos:
      github.com/npikall/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-ultramarine-jellyfish.sh
        container: qc.lic_shabby-cinnabar-bongo
  QC.Met:
    repos:
      github.com/npikall/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-gamboge-harrier.sh
        container: qc.met_snappy-scarlet-wildebeest
  QC.Sec:
    repos:
      github.com/npikall/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-harlequin-zebu.sh
        container: qc.sec_scaly-emerald-zonkey
  QC.Sty:
    repos:
      github.com/npikall/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-magenta-orangutan.sh
        container: qc.sty_stuffy-amethyst-sponge
      github.com/npikall/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-persimmon-spitz.sh
        container: qc.sty_surly-amethyst-whale
      github.com/npikall/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-russet-cat.sh
        container: qc.sty_squirrely-amaranth-spitz
  QC.Uni:
    repos:
      github.com/npikall/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-tan-tarsier.sh
        container: qc.uni_snoopy-cream-chinchilla
  QC.Ver:
    repos:
      github.com/npikall/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-carmine-angelfish.sh
        container: qc.ver_stuffy-taupe-paradise
timeout: 5400
