config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: main
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-red-antelope.sh
        container: qc.acc_slimy-goldenrod-mandrill
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-mauve-bat.sh
        container: qc.doc_wiggy-charcoal-tetra
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-sangria-swan.sh
        container: qc.doc_chummy-eggplant-schnauzer
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-firebrick-hare.sh
        container: qc.doc_lovely-alizarin-bee
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-champagne-cat.sh
        container: qc.doc_stealthy-silver-rabbit
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-cardinal-guppy.sh
        container: qc.lic_grumpy-ecru-millipede
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-burgundy-moorhen.sh
        container: qc.met_homely-magnolia-lion
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-cerise-grasshopper.sh
        container: qc.sec_clammy-lemon-goose
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-aquamarine-uakari.sh
        container: qc.sty_stealthy-vermilion-mongoose
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-cornflower-turkey.sh
        container: qc.sty_tacky-khaki-tzu
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-crimson-clam.sh
        container: qc.sty_hasty-bronze-panda
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.beady-khaki-elephant.sh
        container: qc.uni_homey-corn-coati
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-celadon-hummingbird.sh
        container: qc.ver_grumpy-thistle-donkey
timeout: 5400
