config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/claytharrison/dask-flood-mapper:
      branch: main
      repo: https://github.com/claytharrison/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/claytharrison/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-teal-paradise.sh
        container: qc.acc_lanky-emerald-havanese
  QC.Doc:
    repos:
      github.com/claytharrison/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-tan-ferret.sh
        container: qc.doc_frumpy-rust-shark
      github.com/claytharrison/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-chestnut-quoll.sh
        container: qc.doc_dorky-linen-whippet
      github.com/claytharrison/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-bistre-macaque.sh
        container: qc.doc_jumpy-copper-worm
      github.com/claytharrison/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-amaranth-manatee.sh
        container: qc.doc_crabby-flax-reindeer
  QC.Lic:
    repos:
      github.com/claytharrison/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-corn-paradise.sh
        container: qc.lic_lanky-magnolia-walrus
  QC.Met:
    repos:
      github.com/claytharrison/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-peach-spaniel.sh
        container: qc.met_cozy-mauve-turtle
  QC.Sec:
    repos:
      github.com/claytharrison/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-vermilion-worm.sh
        container: qc.sec_tacky-rose-urchin
  QC.Sty:
    repos:
      github.com/claytharrison/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-mustard-koala.sh
        container: qc.sty_crappy-celadon-affenpinscher
      github.com/claytharrison/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-gold-albatross.sh
        container: qc.sty_droopy-ruby-zonkey
      github.com/claytharrison/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-lime-pig.sh
        container: qc.sty_trippy-champagne-lemur
  QC.Uni:
    repos:
      github.com/claytharrison/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-lime-monster.sh
        container: qc.uni_tacky-ivory-uakari
  QC.Ver:
    repos:
      github.com/claytharrison/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-chestnut-fish.sh
        container: qc.ver_wimpy-bronze-quetzal
timeout: 5400
