config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: thaisbeham-patch-2
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-chestnut-donkey.sh
        container: qc.acc_baggy-cerise-balinese
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-yellow-millipede.sh
        container: qc.doc_frumpy-copper-stoat
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-platinum-vole.sh
        container: qc.doc_nerdy-lime-capybara
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-bronze-zebra.sh
        container: qc.doc_zippy-khaki-monster
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-cobalt-mist.sh
        container: qc.doc_homely-copper-fish
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-charcoal-bullfrog.sh
        container: qc.lic_lumpy-ivory-koala
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-sangria-goose.sh
        container: qc.met_beady-orange-mau
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-violet-emu.sh
        container: qc.sec_pretty-green-quoll
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-lilac-dragon.sh
        container: qc.sty_snappy-olivine-chamois
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-lilac-chipmunk.sh
        container: qc.sty_boozy-thistle-moose
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-yellow-deer.sh
        container: qc.sty_trippy-firebrick-bison
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-silver-clam.sh
        container: qc.uni_bluesy-gamboge-yak
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-dandelion-sheep.sh
        container: qc.ver_sloppy-chestnut-yak
timeout: 5400
