config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: main
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-purple-ibis.sh
        container: qc.acc_randy-cyan-ostrich
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-red-wildebeest.sh
        container: qc.doc_clammy-brass-tortoise
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-lime-buzzard.sh
        container: qc.doc_paltry-salmon-turkey
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-pear-dachshund.sh
        container: qc.doc_thirsty-brass-birman
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-blue-olm.sh
        container: qc.doc_lumpy-teal-donkey
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-red-macaque.sh
        container: qc.lic_lumpy-amethyst-bat
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-khaki-frigatebird.sh
        container: qc.met_paltry-magenta-angora
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-persimmon-raccoon.sh
        container: qc.sec_cozy-emerald-insect
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-aquamarine-fousek.sh
        container: qc.sty_dorky-pear-wolf
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-purple-robin.sh
        container: qc.sty_baggy-lavender-shark
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-xanthic-whippet.sh
        container: qc.sty_gamy-lavender-cattle
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-grey-hedgehog.sh
        container: qc.uni_woolly-white-boar
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-green-woodpecker.sh
        container: qc.ver_surly-silver-ant
timeout: 5400
