config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: thaisbeham-patch-2
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-burgundy-cuscus.sh
        container: qc.acc_breezy-myrtle-panda
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-puce-fly.sh
        container: qc.doc_trippy-carmine-uakari
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-razzmatazz-jellyfish.sh
        container: qc.doc_geeky-cobalt-bracke
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-pumpkin-wrasse.sh
        container: qc.doc_tasty-smalt-lizard
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-ruby-opossum.sh
        container: qc.doc_whiny-wisteria-fly
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-lime-devil.sh
        container: qc.lic_flimsy-smalt-wallaby
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.silly-orange-collie.sh
        container: qc.met_cloudy-rust-jackal
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-silver-liger.sh
        container: qc.sec_scaly-gold-tortoise
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-mauve-opossum.sh
        container: qc.sty_cloudy-crimson-robin
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-bronze-collie.sh
        container: qc.sty_scaly-emerald-dragon
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-flax-mongrel.sh
        container: qc.sty_randy-lime-chameleon
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-indigo-cockroach.sh
        container: qc.uni_shabby-magenta-sponge
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-emerald-whale.sh
        container: qc.ver_thirsty-auburn-dormouse
timeout: 5400
