config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: main
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-xanthic-lemming.sh
        container: qc.acc_skanky-tan-neanderthal
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-bistre-whippet.sh
        container: qc.doc_scanty-lavender-lion
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-teal-chameleon.sh
        container: qc.doc_skanky-dandelion-barracuda
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-amethyst-moorhen.sh
        container: qc.doc_lanky-lemon-stingray
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-xanthic-chameleon.sh
        container: qc.doc_whiny-yellow-deer
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-chestnut-chipmunk.sh
        container: qc.lic_smelly-tangerine-mayfly
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-turquoise-duck.sh
        container: qc.met_skinny-cerulean-zorse
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-ochre-dragonfly.sh
        container: qc.sec_skinny-cardinal-angelfish
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-linen-squid.sh
        container: qc.sty_jumpy-linen-anteater
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-jade-bonobo.sh
        container: qc.sty_homely-corn-rhinoceros
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-chartreuse-starfish.sh
        container: qc.sty_boozy-fuchsia-flounder
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-corn-bordeaux.sh
        container: qc.uni_chewy-rust-eagle
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-teal-beagle.sh
        container: qc.ver_droopy-wheat-armadillo
timeout: 5400
