config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia-test
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: workshop-modified
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-cinnabar-salamander.sh
        container: qc.acc_snoopy-lilac-ferret
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-cyan-macaque.sh
        container: qc.doc_slaphappy-vermilion-wombat
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-pear-ferret.sh
        container: qc.doc_shaggy-ruby-echidna
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-pumpkin-tuatara.sh
        container: qc.doc_lanky-magenta-mandrill
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-wisteria-chinook.sh
        container: qc.lic_frumpy-pumpkin-crab
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-thistle-terrier.sh
        container: qc.met_chewy-khaki-crab
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-ultramarine-sponge.sh
        container: qc.sec_homey-aquamarine-burmese
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cream-heron.sh
        container: qc.sty_blurry-eggplant-mule
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-wheat-zonkey.sh
        container: qc.sty_shabby-fuchsia-barb
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-ecru-lionfish.sh
        container: qc.sty_zippy-champagne-bee
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.homey-amethyst-millipede.sh
        container: qc.uni_ready-mauve-javanese
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-amaranth-sparrow.sh
        container: qc.ver_snappy-chartreuse-hyena
timeout: 5400
