config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/dask-flood-mapper:
      branch: dependabot/github_actions/actions/checkout-5
      repo: https://github.com/interTwin-eu/dask-flood-mapper
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-denim-birman.sh
        container: qc.acc_sleazy-violet-gecko
  QC.Doc:
    repos:
      github.com/interTwin-eu/dask-flood-mapper find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-magenta-shark.sh
        container: qc.doc_beady-platinum-alligator
      github.com/interTwin-eu/dask-flood-mapper git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-grey-cow.sh
        container: qc.doc_skanky-sepia-dolphin
      github.com/interTwin-eu/dask-flood-mapper markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-ochre-dachshund.sh
        container: qc.doc_leaky-mauve-centipede
      github.com/interTwin-eu/dask-flood-mapper restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-aqua-civet.sh
        container: qc.doc_chummy-black-ibis
  QC.Lic:
    repos:
      github.com/interTwin-eu/dask-flood-mapper licensee:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-cerise-centipede.sh
        container: qc.lic_wheezy-cornflower-beaver
  QC.Met:
    repos:
      github.com/interTwin-eu/dask-flood-mapper cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.silly-ochre-dugong.sh
        container: qc.met_sleepy-olive-stingray
  QC.Sec:
    repos:
      github.com/interTwin-eu/dask-flood-mapper bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-tan-leopard.sh
        container: qc.sec_cozy-flax-ant
  QC.Sty:
    repos:
      github.com/interTwin-eu/dask-flood-mapper flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-linen-gibbon.sh
        container: qc.sty_cheeky-celadon-hyrax
      github.com/interTwin-eu/dask-flood-mapper hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-cornflower-zebu.sh
        container: qc.sty_droopy-chestnut-hound
      github.com/interTwin-eu/dask-flood-mapper jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-heliotrope-ostrich.sh
        container: qc.sty_cheeky-coral-armadillo
  QC.Uni:
    repos:
      github.com/interTwin-eu/dask-flood-mapper pytest:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-magenta-otter.sh
        container: qc.uni_lovely-puce-giraffe
  QC.Ver:
    repos:
      github.com/interTwin-eu/dask-flood-mapper get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-zucchini-quoll.sh
        container: qc.ver_hazy-cinnamon-cuscus
timeout: 5400
